[package]
name = "snake"
version = "0.1.0"
authors = ["Nick Vanden Eynde <nick@vitanick.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.2"
piston_window="0.117.0"
